apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc
      containers:
      - name: influxdb
        image: tjinichi/influxdb:000
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/healthcheck.sh"]
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        ports:
        - containerPort: 8086
        volumeMounts:
          - name: influxdb-volume
            mountPath: /var/lib/influxdb

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    component: influxdb
  ports:
    - name: influxdb
      port: 8086
