# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
#   labels:
#     component: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       component: mysql
#   template:
#     metadata:
#       name: mysql
#       labels:
#         component: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: tjinichi/mysql:000
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 3306
#         volumeMounts:
#           - mountPath: /var/lib/mysql
#             name: mysql-claim-volume
#       volumes:
#         - name: mysql-claim-volume
#           persistentVolumeClaim:
#             claimName: mysql-pvc

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
# spec:
#   type: ClusterIP
#   selector:
#     component: mysql
#   ports:
#   - name: mysql
#     port: 3306
#     targetPort: 3306
#     protocol: TCP

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
    - port: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
              claimName: mysql-pvc
      containers:
      - name: mysql
        image: tjinichi/mysql:000
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
