apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
              claimName: mysql-pvc
      containers:
      - name: mysql
        image: tjinichi/mysql:000
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/healthcheck.sh"]
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
    - name: mysql
      port: 3306