apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    component: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: phpmyadmin
  template:
    metadata:
      name: phpmyadmin
      labels:
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: tjinichi/phpmyadmin:000
        imagePullPolicy: Never
        # livenessProbe:
        #   exec:
        #     command: ["/bin/sh", "-c", "pgrep telegraf && pgrep nginx && pgrep php-fpm"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        # env:
        #   - name: SERVICE
        #     value: phpmyadmin
        #   - name: PMA_USER
        #     valueFrom:
        #       secretKeyRef:
        #         name: ft-secret
        #         key: db_user
        #   - name: PMA_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: ft-secret
        #         key: db_pass
        #   - name: PMA_HOST
        #     value: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    component: phpmyadmin
spec:
  selector:
    component: phpmyadmin
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 5000
    targetPort: 443
