apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        component: wordpress
    spec:
      containers:
      - name: wordpress
        image: tjinichi/wordpress:000
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/healthcheck.sh"]
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    component: wordpress
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 5050
    targetPort: 443
