apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      component: ftps
  template:
    metadata:
      labels:
        component: ftps
    spec:
      containers:
      - name: ftps
        image: tjinichi/ftps:000
        imagePullPolicy: Never
        ports:
        - name: ftps
          containerPort: 21
        - name: ftps_passive_0
          containerPort: 21000
        - name: ftps_passive_1
          containerPort: 21001
        - name: ftps_passive_2
          containerPort: 21002
        - name: ftps_passive_3
          containerPort: 21003
        - name: ftps_passive_4
          containerPort: 21004
        - name: ftps_passive_5
          containerPort: 21005

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    component: ftps
  ports:
  - name: ftps
    port: 21
  - name: ftps-passive-0
    port: 21000
  - name: ftps-passive-1
    port: 21001
  - name: ftps-passive-2
    port: 21002
  - name: ftps-passive-3
    port: 21003
  - name: ftps-passive-4
    port: 21004
  - name: ftps-passive-5
    port: 21005